### PR TITLE
acquireToken(resource) now returns Observable<string>

### PR DESCRIPTION
**Pull request by corfor**
I believe fixes issue #15 

Also updates to latest dependencies.

### CODE REVIEW

**Comment by jimbarrett33** [comment]
Hi @corfor. Thanks for the fix to TypeScript but it didn't work for me at runtime until the inner "this" was fixed (unless I don't have the latest code).  I'm not extremely comfortable with this library so I don't want to do a pull request but below is the code I have locally. And I'm just trying to get something to work at this point (which I finally did!)

Thanks,
Jim

```
public acquireToken(resource: string)
    {
       var _this = this;   // save outer this for inner function

       let errorMessage: string;
       return Observable.bindCallback(acquireTokenInternal, function (token: string)
       {
          if (!token && errorMessage)
             throw (errorMessage);
          return token;
       })();

       function acquireTokenInternal(cb: any)
       {
          let s: string = null;

          _this.adalContext.acquireToken(resource, (error: string, tokenOut: string) =>
          {
             if (error)
             {
                _this.adalContext.error('Error when acquiring token for resource: ' + resource, error);
                errorMessage = error;
                cb(<string>null);
             } else
             {
                cb(tokenOut);
                s = tokenOut;
             }
          });
          return s;
       }
    }
```

**Comment by corfor** [comment]
Thanks, @jbarr33 I've checked in your code.

**Comment by jimbarrett33** [comment]
@corfor  No problem. Thanks for integrating it.

**Comment by corfor** [comment]
@sureshchahal, can this be pulled in now and deployed to npm?

**Comment by sureshchahal** [comment]
@corfor : Merged and published.

**Pull request merged**
